# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 928765a997dea54b999ffee8235dede687f1980eb76fc283b64e95b8039a086e69beae9d418e012aa94d1df442a675c11c8ef0118b9f249ec96024411e376347

test:
  secret_key_base: febb006cd7865533177ee3d98c1deeb20dc7591a0effc8f88612a645b5fb54d426fb8dd81166d56506388ec93fa8921b984143da009fcc950c4561b756be3467

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
